require('dotenv').config();
const mongoose = require('mongoose');
const Question = require('./models/Question');

const placementQuestions = [
  // --- ARRAYS & TWO POINTERS ---
  {
    title: 'Two Sum',
    platform: 'LeetCode',
    rating: 800,
    difficulty: 'Easy',
    topics: ['Arrays', 'Hash Map', 'Two Pointers'],
    link: 'https://leetcode.com/problems/two-sum/',
  },
  {
    title: 'Best Time to Buy and Sell Stock',
    platform: 'LeetCode',
    rating: 900,
    difficulty: 'Easy',
    topics: ['Arrays', 'Dynamic Programming', 'Sliding Window'],
    link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
  },
  {
    title: '3Sum',
    platform: 'LeetCode',
    rating: 1400,
    difficulty: 'Medium',
    topics: ['Arrays', 'Two Pointers', 'Sorting'],
    link: 'https://leetcode.com/problems/3sum/',
  },
  {
    title: 'Container With Most Water',
    platform: 'LeetCode',
    rating: 1300,
    difficulty: 'Medium',
    topics: ['Two Pointers', 'Greedy', 'Arrays'],
    link: 'https://leetcode.com/problems/container-with-most-water/',
  },
  {
    title: 'Product of Array Except Self',
    platform: 'LeetCode',
    rating: 1200,
    difficulty: 'Medium',
    topics: ['Arrays', 'Prefix Sum'],
    link: 'https://leetcode.com/problems/product-of-array-except-self/',
  },
  {
    title: 'Maximum Subarray (Kadane Algorithm)',
    platform: 'LeetCode',
    rating: 1100,
    difficulty: 'Medium',
    topics: ['Arrays', 'Dynamic Programming', 'Kadane'],
    link: 'https://leetcode.com/problems/maximum-subarray/',
  },
  {
    title: 'Merge Intervals',
    platform: 'LeetCode',
    rating: 1400,
    difficulty: 'Medium',
    topics: ['Arrays', 'Sorting', 'Intervals'],
    link: 'https://leetcode.com/problems/merge-intervals/',
  },
  {
    title: 'Subarray Sum Equals K',
    platform: 'LeetCode',
    rating: 1400,
    difficulty: 'Medium',
    topics: ['Arrays', 'Hash Map', 'Prefix Sum'],
    link: 'https://leetcode.com/problems/subarray-sum-equals-k/',
  },
  {
    title: 'Trapping Rain Water',
    platform: 'LeetCode',
    rating: 1900,
    difficulty: 'Hard',
    topics: ['Two Pointers', 'Stack', 'Dynamic Programming'],
    link: 'https://leetcode.com/problems/trapping-rain-water/',
  },

  // --- STRINGS & HASH MAP ---
  {
    title: 'Valid Anagram',
    platform: 'LeetCode',
    rating: 800,
    difficulty: 'Easy',
    topics: ['Strings', 'Hash Map', 'Sorting'],
    link: 'https://leetcode.com/problems/valid-anagram/',
  },
  {
    title: 'Group Anagrams',
    platform: 'LeetCode',
    rating: 1200,
    difficulty: 'Medium',
    topics: ['Strings', 'Hash Map', 'Sorting'],
    link: 'https://leetcode.com/problems/group-anagrams/',
  },
  {
    title: 'Longest Substring Without Repeating Characters',
    platform: 'LeetCode',
    rating: 1300,
    difficulty: 'Medium',
    topics: ['Strings', 'Sliding Window', 'Hash Map'],
    link: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
  },
  {
    title: 'Valid Palindrome',
    platform: 'LeetCode',
    rating: 800,
    difficulty: 'Easy',
    topics: ['Strings', 'Two Pointers'],
    link: 'https://leetcode.com/problems/valid-palindrome/',
  },
  {
    title: 'Longest Palindromic Substring',
    platform: 'LeetCode',
    rating: 1500,
    difficulty: 'Medium',
    topics: ['Strings', 'Dynamic Programming'],
    link: 'https://leetcode.com/problems/longest-palindromic-substring/',
  },

  // --- BINARY SEARCH & SLIDING WINDOW ---
  {
    title: 'Search in Rotated Sorted Array',
    platform: 'LeetCode',
    rating: 1300,
    difficulty: 'Medium',
    topics: ['Binary Search', 'Arrays'],
    link: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
  },
  {
    title: 'Find Minimum in Rotated Sorted Array',
    platform: 'LeetCode',
    rating: 1200,
    difficulty: 'Medium',
    topics: ['Binary Search', 'Arrays'],
    link: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',
  },
  {
    title: 'Koko Eating Bananas',
    platform: 'LeetCode',
    rating: 1400,
    difficulty: 'Medium',
    topics: ['Binary Search'],
    link: 'https://leetcode.com/problems/koko-eating-bananas/',
  },
  {
    title: 'Minimum Window Substring',
    platform: 'LeetCode',
    rating: 1900,
    difficulty: 'Hard',
    topics: ['Sliding Window', 'Strings', 'Hash Map'],
    link: 'https://leetcode.com/problems/minimum-window-substring/',
  },

  // --- LINKED LIST ---
  {
    title: 'Reverse Linked List',
    platform: 'LeetCode',
    rating: 800,
    difficulty: 'Easy',
    topics: ['Linked List', 'Recursion'],
    link: 'https://leetcode.com/problems/reverse-linked-list/',
  },
  {
    title: 'Linked List Cycle',
    platform: 'LeetCode',
    rating: 900,
    difficulty: 'Easy',
    topics: ['Linked List', 'Two Pointers'],
    link: 'https://leetcode.com/problems/linked-list-cycle/',
  },
  {
    title: 'Merge Two Sorted Lists',
    platform: 'LeetCode',
    rating: 800,
    difficulty: 'Easy',
    topics: ['Linked List', 'Recursion'],
    link: 'https://leetcode.com/problems/merge-two-sorted-lists/',
  },
  {
    title: 'Remove Nth Node From End of List',
    platform: 'LeetCode',
    rating: 1200,
    difficulty: 'Medium',
    topics: ['Linked List', 'Two Pointers'],
    link: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
  },
  {
    title: 'Reorder List',
    platform: 'LeetCode',
    rating: 1400,
    difficulty: 'Medium',
    topics: ['Linked List', 'Two Pointers', 'Stack'],
    link: 'https://leetcode.com/problems/reorder-list/',
  },

  // --- TREES & BINARY SEARCH TREES ---
  {
    title: 'Invert Binary Tree',
    platform: 'LeetCode',
    rating: 800,
    difficulty: 'Easy',
    topics: ['Trees', 'Recursion', 'BFS/DFS'],
    link: 'https://leetcode.com/problems/invert-binary-tree/',
  },
  {
    title: 'Maximum Depth of Binary Tree',
    platform: 'LeetCode',
    rating: 800,
    difficulty: 'Easy',
    topics: ['Trees', 'Recursion', 'BFS/DFS'],
    link: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
  },
  {
    title: 'Lowest Common Ancestor of BST',
    platform: 'LeetCode',
    rating: 1100,
    difficulty: 'Medium',
    topics: ['Trees', 'Binary Search', 'Recursion'],
    link: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',
  },
  {
    title: 'Binary Tree Level Order Traversal',
    platform: 'LeetCode',
    rating: 1200,
    difficulty: 'Medium',
    topics: ['Trees', 'BFS/DFS'],
    link: 'https://leetcode.com/problems/binary-tree-level-order-traversal/',
  },
  {
    title: 'Validate Binary Search Tree',
    platform: 'LeetCode',
    rating: 1300,
    difficulty: 'Medium',
    topics: ['Trees', 'Recursion', 'Binary Search'],
    link: 'https://leetcode.com/problems/validate-binary-search-tree/',
  },

  // --- DYNAMIC PROGRAMMING (PLACEMENT ESSENTIALS) ---
  {
    title: 'Climbing Stairs',
    platform: 'LeetCode',
    rating: 800,
    difficulty: 'Easy',
    topics: ['Dynamic Programming', 'Math'],
    link: 'https://leetcode.com/problems/climbing-stairs/',
  },
  {
    title: 'Coin Change',
    platform: 'LeetCode',
    rating: 1500,
    difficulty: 'Medium',
    topics: ['Dynamic Programming', 'BFS/DFS'],
    link: 'https://leetcode.com/problems/coin-change/',
  },
  {
    title: 'Longest Increasing Subsequence (LIS)',
    platform: 'LeetCode',
    rating: 1500,
    difficulty: 'Medium',
    topics: ['Dynamic Programming', 'Binary Search'],
    link: 'https://leetcode.com/problems/longest-increasing-subsequence/',
  },
  {
    title: 'Longest Common Subsequence (LCS)',
    platform: 'LeetCode',
    rating: 1500,
    difficulty: 'Medium',
    topics: ['Dynamic Programming', 'Strings'],
    link: 'https://leetcode.com/problems/longest-common-subsequence/',
  },
  {
    title: 'Word Break',
    platform: 'LeetCode',
    rating: 1400,
    difficulty: 'Medium',
    topics: ['Dynamic Programming', 'Hash Map', 'Strings'],
    link: 'https://leetcode.com/problems/word-break/',
  },
  {
    title: 'House Robber',
    platform: 'LeetCode',
    rating: 1100,
    difficulty: 'Medium',
    topics: ['Dynamic Programming', 'Arrays'],
    link: 'https://leetcode.com/problems/house-robber/',
  },
  {
    title: 'Partition Equal Subset Sum',
    platform: 'LeetCode',
    rating: 1500,
    difficulty: 'Medium',
    topics: ['Dynamic Programming', 'Arrays'],
    link: 'https://leetcode.com/problems/partition-equal-subset-sum/',
  },
  {
    title: 'Edit Distance',
    platform: 'LeetCode',
    rating: 1800,
    difficulty: 'Hard',
    topics: ['Dynamic Programming', 'Strings'],
    link: 'https://leetcode.com/problems/edit-distance/',
  },

  // --- GRAPHS & BACKTRACKING ---
  {
    title: 'Number of Islands',
    platform: 'LeetCode',
    rating: 1300,
    difficulty: 'Medium',
    topics: ['Graph', 'BFS/DFS', 'Recursion'],
    link: 'https://leetcode.com/problems/number-of-islands/',
  },
  {
    title: 'Course Schedule (Topological Sort)',
    platform: 'LeetCode',
    rating: 1500,
    difficulty: 'Medium',
    topics: ['Graph', 'BFS/DFS', 'Topological Sort'],
    link: 'https://leetcode.com/problems/course-schedule/',
  },
  {
    title: 'Word Search',
    platform: 'LeetCode',
    rating: 1400,
    difficulty: 'Medium',
    topics: ['Graph', 'Backtracking', 'Arrays'],
    link: 'https://leetcode.com/problems/word-search/',
  },
  {
    title: 'Combination Sum',
    platform: 'LeetCode',
    rating: 1300,
    difficulty: 'Medium',
    topics: ['Backtracking', 'Arrays'],
    link: 'https://leetcode.com/problems/combination-sum/',
  },
  {
    title: 'N-Queens',
    platform: 'LeetCode',
    rating: 1900,
    difficulty: 'Hard',
    topics: ['Backtracking'],
    link: 'https://leetcode.com/problems/n-queens/',
  },

  // --- STACK, QUEUE & HEAP ---
  {
    title: 'Valid Parentheses',
    platform: 'LeetCode',
    rating: 800,
    difficulty: 'Easy',
    topics: ['Stack', 'Strings'],
    link: 'https://leetcode.com/problems/valid-parentheses/',
  },
  {
    title: 'Min Stack',
    platform: 'LeetCode',
    rating: 1200,
    difficulty: 'Medium',
    topics: ['Stack', 'Design'],
    link: 'https://leetcode.com/problems/min-stack/',
  },
  {
    title: 'Top K Frequent Elements',
    platform: 'LeetCode',
    rating: 1300,
    difficulty: 'Medium',
    topics: ['Heap', 'Hash Map', 'Sorting'],
    link: 'https://leetcode.com/problems/top-k-frequent-elements/',
  },
  {
    title: 'Merge k Sorted Lists',
    platform: 'LeetCode',
    rating: 1800,
    difficulty: 'Hard',
    topics: ['Heap', 'Linked List', 'Divide and Conquer'],
    link: 'https://leetcode.com/problems/merge-k-sorted-lists/',
  },

  // --- CODEFORCES MUST-SOLVE CP CLASSICS ---
  {
    title: 'Watermelon',
    platform: 'Codeforces',
    rating: 800,
    difficulty: 'Easy',
    topics: ['Math', 'Implementation'],
    link: 'https://codeforces.com/problemset/problem/4/A',
    contestId: '4',
    problemIndex: 'A',
  },
  {
    title: 'Way Too Long Words',
    platform: 'Codeforces',
    rating: 800,
    difficulty: 'Easy',
    topics: ['Strings', 'Implementation'],
    link: 'https://codeforces.com/problemset/problem/71/A',
    contestId: '71',
    problemIndex: 'A',
  },
  {
    title: 'Team',
    platform: 'Codeforces',
    rating: 800,
    difficulty: 'Easy',
    topics: ['Implementation', 'Greedy'],
    link: 'https://codeforces.com/problemset/problem/231/A',
    contestId: '231',
    problemIndex: 'A',
  },
  {
    title: 'Theatre Square',
    platform: 'Codeforces',
    rating: 1000,
    difficulty: 'Easy',
    topics: ['Math'],
    link: 'https://codeforces.com/problemset/problem/1/A',
    contestId: '1',
    problemIndex: 'A',
  },
  {
    title: 'Next Round',
    platform: 'Codeforces',
    rating: 800,
    difficulty: 'Easy',
    topics: ['Implementation'],
    link: 'https://codeforces.com/problemset/problem/158/A',
    contestId: '158',
    problemIndex: 'A',
  },
  {
    title: 'Domino piling',
    platform: 'Codeforces',
    rating: 800,
    difficulty: 'Easy',
    topics: ['Math', 'Greedy'],
    link: 'https://codeforces.com/problemset/problem/50/A',
    contestId: '50',
    problemIndex: 'A',
  },
  {
    title: 'Bit++',
    platform: 'Codeforces',
    rating: 800,
    difficulty: 'Easy',
    topics: ['Implementation'],
    link: 'https://codeforces.com/problemset/problem/282/A',
    contestId: '282',
    problemIndex: 'A',
  },
  {
    title: 'Beautiful Matrix',
    platform: 'Codeforces',
    rating: 800,
    difficulty: 'Easy',
    topics: ['Implementation'],
    link: 'https://codeforces.com/problemset/problem/263/A',
    contestId: '263',
    problemIndex: 'A',
  },
  {
    title: 'Elephant',
    platform: 'Codeforces',
    rating: 800,
    difficulty: 'Easy',
    topics: ['Math', 'Greedy'],
    link: 'https://codeforces.com/problemset/problem/617/A',
    contestId: '617',
    problemIndex: 'A',
  },
  {
    title: 'Young Physicist',
    platform: 'Codeforces',
    rating: 1000,
    difficulty: 'Easy',
    topics: ['Math', 'Implementation'],
    link: 'https://codeforces.com/problemset/problem/69/A',
    contestId: '69',
    problemIndex: 'A',
  },
  {
    title: 'Registration system',
    platform: 'Codeforces',
    rating: 1300,
    difficulty: 'Medium',
    topics: ['Data Structures', 'Hash Map', 'Strings'],
    link: 'https://codeforces.com/problemset/problem/4/C',
    contestId: '4',
    problemIndex: 'C',
  },
  {
    title: 'K-th Not Divisible by n',
    platform: 'Codeforces',
    rating: 1200,
    difficulty: 'Medium',
    topics: ['Binary Search', 'Math'],
    link: 'https://codeforces.com/problemset/problem/1352/C',
    contestId: '1352',
    problemIndex: 'C',
  },
  {
    title: 'Woodcutters',
    platform: 'Codeforces',
    rating: 1500,
    difficulty: 'Hard',
    topics: ['Dynamic Programming', 'Greedy'],
    link: 'https://codeforces.com/problemset/problem/545/C',
    contestId: '545',
    problemIndex: 'C',
  },
  // --- ATCODER CP ESSENTIALS ---
  {
    title: 'Frog 1',
    platform: 'AtCoder',
    rating: 1100,
    difficulty: 'Easy',
    topics: ['Dynamic Programming'],
    link: 'https://atcoder.jp/contests/dp/tasks/dp_a',
  },
  {
    title: 'Frog 2',
    platform: 'AtCoder',
    rating: 1200,
    difficulty: 'Medium',
    topics: ['Dynamic Programming'],
    link: 'https://atcoder.jp/contests/dp/tasks/dp_b',
  },
  {
    title: 'Knapsack 1',
    platform: 'AtCoder',
    rating: 1400,
    difficulty: 'Medium',
    topics: ['Dynamic Programming'],
    link: 'https://atcoder.jp/contests/dp/tasks/dp_d',
  },
  {
    title: 'Longest Path',
    platform: 'AtCoder',
    rating: 1600,
    difficulty: 'Hard',
    topics: ['Graph', 'Dynamic Programming'],
    link: 'https://atcoder.jp/contests/dp/tasks/dp_g',
  }
];

const seedDB = async () => {
  try {
    if (!process.env.MONGO_URI) {
      console.error('Error: MONGO_URI is missing in .env');
      process.exit(1);
    }
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB Connected for Seeding Placement Problems...');

    for (const q of placementQuestions) {
      await Question.updateOne(
        { title: q.title, platform: q.platform },
        { $set: q },
        { upsert: true }
      );
    }

    const count = await Question.countDocuments();
    console.log(`Seeding successful! Total questions in DB: ${count}`);
    process.exit(0);
  } catch (error) {
    console.error('Seeding failed:', error.message);
    process.exit(1);
  }
};

seedDB();
